name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.8', '3.10' ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install pdftotext
        run: sudo apt-get install poppler-utils
      - name: npm ci
        run: npm ci
      # https://github.com/actions/setup-python/blob/main/docs/advanced-usage.md#caching-packages
      - name: Install poetry
        run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'poetry'
      - run: poetry install -E import-json
      - name: Test migrations
        # Ensure our migrations are working (squashing can cause weird problems)
        run: ENV_PATH=etc/test.env .venv/bin/python ./manage.py migrate
      - name: Build assets
        run: |
          npm run build:prod
          npm run build:dev
      - name: Run tests
        run: .venv/bin/pytest
